database:
    driver    : mysql
    host      : 127.0.0.1
    port      : 3306
    database  : db_commodity_management
    username  : root
    password  : root 
    charset   : utf8
    collation : utf8_unicode_ci
